import '../compiler_context.dart';
import '../generator.dart';
import '../generator_priority/module_generator_priority.dart';
import '../module.dart';

class ModuleHeaderGenerator implements ModuleGenerator {
  const ModuleHeaderGenerator();

  @override
  int get priority => ModuleGeneratorPriority.header.index;

  @override
  void generate(CompilerContext context, StringBuffer buffer, Module module) {
    buffer.write(
      '// ** WARNING **\n'
      '// This file is autogenerated by Javelin Object Compiler (joc).\n'
      '// Do not edit it directly.\n'
      '//\n'
      '// ignore_for_file: annotate_overrides\n' // TODO: Remove.
      '// ignore_for_file: deprecated_member_use_from_same_package\n'
      '// ignore_for_file: directives_ordering\n'
      '// ignore_for_file: prefer_const_constructors_in_immutables\n'
      '// ignore_for_file: sort_constructors_first\n'
      '// ignore_for_file: unused_import\n',
    );
  }
}
