// ** WARNING **
// This file is autogenerated by Javelin Object Compiler (joc).
// Do not edit it directly.
//
// ignore_for_file: annotate_overrides
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: directives_ordering
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: sort_constructors_first
// ignore_for_file: unused_import
import 'package:javelin_object/jo_internal.dart';

@immutable
class Void {
  const Void();

  factory Void.fromString(String s) => Void.fromMap(fromJoText(s));

  factory Void.fromBytes(Uint8List bytes) => Void.fromJoFieldMap0(parseJoBinary(bytes));

  Void.fromJoFieldMap0(Map<int, JoFieldData> map);

  Void.fromMap(Map<Object?, Object?> map);

  Uint8List toBytes() => encodeBytes().toBytes();

  JoBinaryEncoder encodeBytes([JoBinaryEncoder? $derivedEncoder]) {
    final encoder = JoBinaryEncoder();
    return encoder;
  }

  Map<String, Object?> toMap() => const {};

  @override
  String toString({bool pretty = true}) =>
    toJoText(toMap(), pretty: pretty);

}

void joRegister() {}
