name: javelin_object
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  pedantic: ^1.10.0
dependencies: 
  collection: ^1.15.0
  meta: ^1.3.0
  postgres: ^2.3.2
  test: ^1.16.0
  yaml: ^3.1.0
